/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:15a39684-7199-470b-a57a-ef14d39a3a3c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_10KEy913q",
    "aws_user_pools_web_client_id": "76j19eqjg3lahi3f988nc32q4m",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "predictions": {
        "identify": {
            "identifyEntities": {
                "proxy": false,
                "region": "us-west-2",
                "celebrityDetectionEnabled": true
            },
            "identifyText": {
                "proxy": false,
                "region": "us-west-2",
                "defaults": {
                    "format": "ALL"
                }
            }
        },
        "interpret": {
            "interpretText": {
                "region": "us-west-2",
                "proxy": false,
                "defaults": {
                    "type": "ENTITIES"
                }
            }
        }
    }
};


export default awsmobile;
